---
Description: PrintService
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  printUsername:
    Type: String
    Description: print username
  printPassword:
    Type: String
    Description: print password
  loggingEnvironment:
    Type: String
    Description: Logging Environment
  loggingMaxInnerExceptionDepth:
    Type: Number
    Description: Logging Max Inner Exception Depth
  environmentSuffix:
    Type: String
    AllowedValues:
      - ''
      - -int
      - -sys
    Description: Environment suffix e.g -int -sys
  TestClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of test cluster
    Default: TestClusterName
  ProductionClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of production cluster
    Default: ProductionClusterName

Conditions:
  isTesting: !Or
    - !Equals [!Ref environmentSuffix, "-int"]
    - !Equals [!Ref environmentSuffix, "-sys"]

Resources:
  printServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: "Project"
          Value: "printService"
        - Key: "CIT"
          Value: "IT"
        - Key: AppManagerCFNStackKey
          Value: !Sub ${AWS::StackId}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["ecs-tasks.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      Path: "/"
      Policies:
        - PolicyName: printServiceServices
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  Fn::ImportValue: logging-queue-arn
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
        - PolicyName: kms
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                Resource: "*"
        - PolicyName: s3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub "arn:aws:s3:::auth${environmentSuffix}*-keysbucket*"
  StackLogGroup: 
    Type: AWS::LogService::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-LogGroup}
      RetentionInDays: 14
        
  printServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Tags:
        - Key: "Project"
          Value: "printService"
        - Key: "CIT"
          Value: "IT"
        - Key: AppManagerCFNStackKey
          Value: !Sub ${AWS::StackId}
      TaskRoleArn: !GetAtt printServiceRole.Arn
      ContainerDefinitions:
        - Name: printService
          Cpu: '1'
          Essential: 'true'
          Image: !Sub docker.io/linn/print-service:${dockerTag}
          PortMappings:
            - ContainerPort: 5050
          Memory: '250'
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "curl -f http://localhost:5050/healthcheck || exit 1"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref StackLogGroup
              awslogs-stream prefix: !Ref AWS::StackName
          Environment:
            - Name: PRINT_USERNAME
              Value: !Ref printUsername
            - Name: PRINT_PASSWORD
              Value: !Ref printPassword
            - Name: LOG_AMAZON_SQSQUEUEURI
              Value: !ImportValue logging-queue-url
            - Name: LOG_ENVIRONMENT
              Value: !Ref loggingEnvironment
            - Name: LOG_MAX_INNER_EXCEPTION_DEPTH
              Value: !Ref loggingMaxInnerExceptionDepth
            - Name: awsRegion
              Value: !Ref AWS::Region
            - Name: KEYS_BUCKET_NAME
              Value:
                Fn::ImportValue:
                  !Sub "linn-keys-bucket${environmentSuffix}"
            - Name: KMS_KEY_ALIAS
              Value:
                Fn::ImportValue:
                  !Sub "kms-key-alias${environmentSuffix}"
          DockerLabels:
            traefik.enable: "true"
            traefik.http.routers.printservice.entrypoints: "web"
            traefik.http.routers.printservice.rule: "PathPrefix(`/print-service/`)"
            traefik.http.services.printservice.loadbalancer.healthcheck.path: "/healthcheck"
           
  printServiceService:
    Type: AWS::ECS::Service
    Properties:
      # Have to use long form conditional
      Cluster: !If
        - isTesting
        - !Sub ${TestClusterName}
        - !Sub ${ProductionClusterName}
      DesiredCount: !If [ isTesting, 1, 2 ]
      PlacementStrategies:
        - Field: attribute:ecs.availability-zone
          Type: spread
        - Field: instanceId
          Type: spread
      TaskDefinition: !Ref printServiceTaskDefinition